chore: Fix pre-commit hook output format [skip ci]

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -97,8 +97,11 @@ do
     fi
 	fi
 done
-if [ FMTFAILED = 0 ]; then
+if [ "$FMTFAILED" = 0 ]; then
   printf "${SUCCESS}\n"
+else
+	printf "${FAILURE}\n"
+	exit 1
 fi
 
 exit "$FAILED"
